//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Users = new HashSet<User>();
        }
    
        public int PaymentID { get; set; }
        public string PackageDetails { get; set; }
        public int PackagePrice { get; set; }
        public int Discount { get; set; }
        public int AdditionalPayment { get; set; }
        public int TotalAmount { get; set; }
        public string AuthorityIdentification { get; set; }
        public string date { get; set; }
        public int Finalamount { get; set; }
        public int Discountamount { get; set; }
        public int CustomerID { get; set; }
        public int EventID { get; set; }
    
        public virtual CustomerR CustomerR { get; set; }
        public virtual EventR EventR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
