//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UEvent
    {
        public int UEventID { get; set; }
        public string EventName { get; set; }
        public string EventCatgory { get; set; }
        public string TimeDuration { get; set; }
        public string Date { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual EventR EventR { get; set; }
    }
}
